version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: ./gradlew build -x test
      - run: ./gradlew test
      - run: >
          ./gradlew sonarqube 
          -Dsonar.projectKey=${SONAR_KEY} 
          -Dsonar.organization=${SONAR_ORGANZATION} 
          -Dsonar.host.url=${SONAR_HOST} 
          -Dsonar.login=${SONAR_LOGIN_TOKEN} 
          -Dsonar.pullrequest.provider=github 
          -Dsonar.pullrequest.github.repository=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} 
          -Dsonar.pullrequest.github.endpoint=https://api.github.com/ 
          -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} 
          -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} 
          -Dsonar.pullrequest.base=master 
